language: cpp
os: linux
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - cmake
      - cmake-data

compiler: g++

branches: 
  only:
    - server